### ISSUE TITLE
Details Page

### ISSUE THREAD

**Issue by SaschaRadojkovic** [SaschaRadojkovic/capstone-project#13]
## Value Proposition

**As a**User
**I want to** be able to scan a product using my device's camera
**so that** view detailed information about the product on a separate page, with the option to return to the scanner screen. If the product is not found, a message should be displayed on the scanner screen.
​

## Description

![image](https://user-images.githubusercontent.com/16897094/214813540-12c9c41c-d673-4b15-9eee-0632a31b3575.png)

​
## Acceptance Criteria

- [ ] The scanned product's information is displayed on a separate page
- [ ] The details page includes a button or link that allows users to return to the scanner screen
- [ ] If a product is not found, a message is displayed on the scanner screen
- [ ] The functionality is tested and works on various devices

      ​
## Tasks

- [ ] fetch the [openfoodfacts ](https://de.openfoodfacts.org/)API product database that can be queried when a product is scanned
- [ ] Implement a details page that displays information about the product
- [ ] Add a button or link on the details page that allows users to return to the scanner screen
- [ ] Handle the case where a product is not found and display a message on the scanner screen
- [ ] Test the functionality on various devices
      ​
## Complexity

... (T-Shirt Sizes XS to XL)

**Comment by JoergWolff** [comment]
WOW Sascha. LGTM
