### ISSUE TITLE
Save Products

### ISSUE THREAD

**Issue by SaschaRadojkovic** [SaschaRadojkovic/capstone-project#15]
## Value Proposition

**As a**User 
**I want to** be able to save products that i can eat  
**so that** i can watch them in a seperate products page 
​

## Description

![image](https://user-images.githubusercontent.com/16897094/215040031-c39c505f-cfc2-4313-9d2d-cfea5f67e3cb.png)
​

## Acceptance Criteria

- [ ] The user should be able to view the details of the scanned product, including its name, image, brand ,additives and allergens
- [ ] The user should be able to save the product to a list of "eatable products" for future reference
- [ ] The user should be able to view their list of saved "eatable products" on a separate "products" page
- [ ] The user should be able to remove a product from their list of saved products
      ​

## Tasks

- [ ] Add a button or link on the product details page for the user to save the product
Implement a way to store the saved products in localstorage
- [ ] Create a separate "products" page where the user can view their list of saved products
- [ ] Create a new navigation link for saved products
- [ ] Add a button or link on the products page for the user to remove a product from their list
- [ ] Add a way to confirm the removal of a product before it is permanently deleted
- [ ] Add a way to be able to delete the product  that is saved.
      ​

## Complexity

... (T-Shirt Sizes XS to XL)
