### ISSUE TITLE
Basic Styling

### ISSUE THREAD

**Issue by SaschaRadojkovic** [SaschaRadojkovic/capstone-project#16]
## Value Proposition

**As a** developer 
**I want to** have a basic styling 
**so that** i can navigate better throught
​

## Description

... (Wireframe, scribble, design or text)
​

## Acceptance Criteria

- [ ] The navigation menu is styled and easily visible
- [ ] Buttons have a consistent look and feel

      ​

## Tasks

- [ ] Implement basic styling for all components
- [ ] Style the navigation menu
- [ ] Style all buttons and Links in the application

      ​

## Complexity

... (T-Shirt Sizes S - M )

**Comment by Long-HaHoang** [comment]
Hi Sascha,

Can you remove the `...` from your complexity.

You also have empty code blocks.

There is typo in `so that` section. You have `i` instead of `I` capital letter.

Can you also add more description. 

There is no point to create a user story if you don't know the general look, yet.
You can try styling outside of an user story and later create one a more precise description about what you want to do.

I'm mean if you remove all styling you get a consistent look and feel, too. (Late 90` early 2000)

Try using excalidraw or figma to get an overall layout. By then, you should be able give an more concise complexity, too.

**Comment by SaschaRadojkovic** [comment]
hi Long , thanks for your advice. I don't know why I have empty code blocks here because in the edit mode  there is nothing to see , maybe you know what that could be . <img width="665" alt="Bildschirmfoto 2023-01-29 um 13 14 51" src="https://user-images.githubusercontent.com/16897094/215325525-87d8a73d-7581-4c78-95f3-c791b7d534c6.png">   I understand what you are saying about the styling and the real workflow (even i have made some tests in figma and excalidraw )in the business world i would of course not do it like that . But in fact it is my own project somehow and I thought i have the freedom even to do things a little bit different than later. I have a general idea about the look of my app but I would have the possibility to change that on the fly  without  having problems with not matching the user story.  But i think  you are right and it is not best practice. Thank you for taking your time and reviewing my code . I am not shure how i will change this user story. So it will stay for now unchecked ;)

**Comment by SaschaRadojkovic** [comment]
> Yeah, you always come back to this story if have the styling idea. I found it kind of an odd story because it's looks so empty 🤣
> 
> I guess it's the empty lines below your `##Acceptance Criteria` and `##Tasks`. I think Github sees those big empty spaces as code blocks.
yes it is the empty line below the task and criteria

**Comment by Long-HaHoang** [comment]
Looks simple enough.
Just one more thing. You could darken or blur the background to heighten the contrast between the background and user interface elements.
As for the green. It's a design choice but the colors red and green are difficult for someone with red-green color blindness

**Comment by Long-HaHoang** [comment]
> -[ ] add credits to the picture artist [Lukas Blazek](https://unsplash.com/@goumbik?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText) auf [Unsplash](https://unsplash.com/de/s/fotos/food?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText)

There is a mix-up between English and German. `auf` instead of `on`
