### ISSUE TITLE
Add Header

### ISSUE THREAD

**Issue by SaschaRadojkovic** [SaschaRadojkovic/capstone-project#17]
## Value Proposition

**As a** User
**I want to** have a App Header 
**so that** i have the feeling of beeing in the same app
​

## Description

... (Wireframe, scribble, design or text)
​

## Acceptance Criteria

- [ ] There should be a Header with the Apps name
- [ ] This  should be visible on every screen

      ​

## Tasks

- [ ] add a Header Component 
- [ ] implement the header Component to the `_app.js `

      ​

## Complexity

... (T-Shirt Sizes XS)

**Comment by Long-HaHoang** [comment]
Hi Sascha,
it seems like every story of your have the `...` in the complexity. ( Removing it, is part of the requirement)

>  name: Userstory template
>  about: |
>  A template to create user stories.
>  Remove all ... and examples before posting.
>  labels: enhancement

You should also remove those empty code blocks.
First of all the code block doesn't make sense in the acceptance criteria.
Because as a customer want to see the criteria not the code.
You can add it to the tasks, but only if you need it.

## Acceptance Criteria

- Try to use whole sentences
>  - [ ] The header with the app name is displayed on top
- There is typo in the second criteria.

## Tasks

- Overall ok. Nothing much to do
- You should start the sentence with a capital letter
