### ISSUE TITLE
Edit Details Page with Personal Notes

### ISSUE THREAD

**Issue by SaschaRadojkovic** [SaschaRadojkovic/capstone-project#18]
## Value Proposition

**As a** User  
**I want to** edit the details page  
**so that** add notes such as the shopping location 
​

## Description

![image](https://user-images.githubusercontent.com/16897094/215268586-f8c0246f-fe31-4c8f-bf5c-f7577a4a6579.png)
​

## Acceptance Criteria

- [ ] The user should be able to access the details page for a specific product by clicking on it in the list of products.
- [ ] On the details page, there should be edit button that leads to a form or text field where the user can input additional notes about the product.
- [ ] The user should be able to save the notes by clicking on a save button or by pressing the enter key.
- [ ] The notes should be displayed on the details page and should be editable by the user at any time.
- [ ] The notes should also be saved in the local storage, so that they persist even if the user refreshes the page.
      ​

## Tasks

- [ ] Create a form or text field on the details page for the user to input notes.
- [ ] Add an event listener for the form's 'submit' event or the text field's 'enter' key press event.
- [ ] Create a function to handle the event and save the notes in the local storage.
- [ ] Display the notes on the details page.
- [ ] Add an 'edit' button or make the notes editable by clicking on them, so that the user can update their notes.
- [ ] Update the local storage with the new notes when the user saves the changes.
- [ ] Add styling to the form and notes to make them more user-friendly.
      ​

## Complexity

... (T-Shirt Sizes L)

**Comment by Long-HaHoang** [comment]
Hi Sascha,
just remove the `...` from the complexity and you are good to go.

You get a ✅ anyway.
