### ISSUE TITLE
Additives

### ISSUE THREAD

**Issue by SaschaRadojkovic** [SaschaRadojkovic/capstone-project#2]
## Value Proposition

**As a** User
**I want to** be able to search for the e food additives( e.g. e528, e 500 etc) .
**so that** i can and add them to a separate list wich appears when i press the button Additives.
​

## Description

![image](https://user-images.githubusercontent.com/16897094/213457010-dfba87e8-381a-4adc-a922-cd8d47a5716a.png)​

## Acceptance Criteria

- [ ] when button additive is clicked show additive list.
- [ ] when typing in search bar show additives
- [ ] when button allergenic is clicked show allergenic list.
 
      ​

## Tasks

- [ ] add additive button 
- [ ] add the logic with useState and TurneryOperator to render allergenic or additives

      ​

## Complexity

... (T-Shirt Sizes S)

**Comment by RobinWitt** [comment]
Hey Sascha, seems to me like you get a feel for the size of a user story!

One Question would be if your search results appear as the user types in the input, or after submitting.
Maybe you can clarify that.

**Comment by SaschaRadojkovic** [comment]
thank you robin , the search results appears directly while searching  i thought that acceptance criteria nr 2 explained that. but i changed it now to be clearer

**Comment by RobinWitt** [comment]
Alrighty :)
