### ISSUE TITLE
create login

### ISSUE THREAD

**Issue by SaschaRadojkovic** [SaschaRadojkovic/capstone-project#21]
## Value Proposition

**As a** user 
**I want to** have a login 
**so that** i can personalize my data  
​

## Description

install the nextauth package and read documentation 
​

## Acceptance Criteria

- [ ] The login page should have a form with fields for email and password.
- [ ] The email should be a valid email format.
- [ ] The password should be at least 8 characters long.
- [ ] The form should have a submit button.
- [ ] On successful submission of the form, the user should be redirected to their personalized dashboard.
- [ ] On incorrect login credentials, the user should receive an error message.

      ​

## Tasks

- [ ] Create a login page with a form for email and password.
- [ ] Implement validation for the email field to accept only valid email formats.
- [ ] Implement validation for the password field to accept only passwords of at least 8 characters long.
- [ ]Add a submit button to the form.
- [ ] Implement authentication using nextauth to check if the login credentials are correct.
- [ ] Redirect the user to their personalized dashboard on successful login.
- [ ] Show an error message on the login page if the login credentials are incorrect.
      ​

## Complexity

(T-Shirt Sizes  XL)

**Comment by RobinWitt** [comment]
nice User Story, happy coding!
