### ISSUE TITLE
nextAuth login

### ISSUE THREAD

**Issue by SaschaRadojkovic** [SaschaRadojkovic/capstone-project#23]
## Value Proposition

**As a** user 
**I want to** I want to be able to log in to the website using my Google account
**so that** i can personalize my data  
​

## Description

install the nextauth package and read documentation 
​

## Acceptance Criteria

- [ ] The login page should have a button for logging in with Google or/and Github.
- [ ] When I click the Google or/and Github login button, I should be redirected to Google's or/and Github authentication page to log in.
- [ ] Upon successful login, I should be redirected to the home page and my name should be displayed on the page to indicate that I am logged in.
- [ ] I should be able to log out at any time.
      ​

## Tasks

- [ ] Set up Google or/and Github authentication using the Google API or/and Github API.
- [ ] Implement the Google or/and Github login button on the login page.
- [ ] On successful login, redirect the user to the home page and display their name.
- [ ] Implement a logout feature that allows the user to log out at any time.​

## Complexity

(T-Shirt Sizes  L)
