### ISSUE TITLE
Mongodb Atlas

### ISSUE THREAD

**Issue by SaschaRadojkovic** [SaschaRadojkovic/capstone-project#24]
## Value Proposition

**As a**User
**I want to**  I want to be able to save my data persistently 
**so that**I can use any browser without losing my data
​

​

## Acceptance Criteria

- [x] The website should have the ability to connect to a MongoDB Atlas database.
- [x] The data that I input on the website should be stored in the three collections in the MongoDB Atlas database (additives, allergens, and products).
- [x] When I log in, the website should retrieve my data from the relevant collection in the MongoDB Atlas database and display it on the page.
- [x] The data should be updated in real-time in the relevant collection in the MongoDB Atlas database as I make changes on the website.
- [x] The website should continue to work even if there is a temporary loss of connection to the MongoDB Atlas database.

## Tasks

- [x] Set up a MongoDB Atlas database and obtain the connection details.
- [x] Create three collections in the MongoDB Atlas database for additives, allergens, and products.
- [x] Integrate the MongoDB Atlas database with the website.
- [x] Store data input by the user in the relevant collection in the MongoDB Atlas database.
- [x] Retrieve the data from the relevant collection in the MongoDB Atlas database and display it on the website when the user logs in.
- [x] Implement real-time updates to the relevant collection in the MongoDB Atlas database as the user makes changes on the website.
- [x] Add error handling for temporary loss of connection to the MongoDB Atlas database.
      ​

## Complexity

(T-Shirt Sizes XL)
