### ISSUE TITLE
some final fixes

### ISSUE THREAD

**Issue by SaschaRadojkovic** [SaschaRadojkovic/capstone-project#26]
## Value Proposition

**As a** Developer 
**I want to** fix some styling and aria-label issues
**so that**the app development is coming to a final version 
​

## Description

​

## Acceptance Criteria

- [ ] every button should be accessible
- [ ] all aria-labels should be in german 
- [ ] all styling parts should be clear and cleand up
      ​

## Tasks

- [ ] change all aria labels to german 
- [ ] fix some boxes they are overlaying

      ​

## Complexity
 (T-Shirt Sizes S)
