### ISSUE TITLE
Allergene Component

### ISSUE THREAD

**Issue by SaschaRadojkovic** [SaschaRadojkovic/capstone-project#4]
## Value Proposition

**As a** user
**I want to** be able to switch from allergenes to additives 
**so that** i can see a list of them
​

## Description

![image](https://user-images.githubusercontent.com/16897094/213700602-116991b7-aa65-488e-b827-567adcd87500.png)
​

## Acceptance Criteria

- [ ] The user can switch between viewing a list of allergens and a list of additives
- [ ] The lists are hardcoded and displayed correctly
- [ ] The switch is clearly visible and easy to use
      ​

## Tasks
 -[ ] download and import the additive database from [here](https://de.openfoodfacts.org/additives.json) to your project
 -[ ] Create a additive card component which is very similar to the allergene card component (copy the allergene card component and change needed values)
- [ ] Create a additive button to toggle between the two lists
- [ ] Display list of allergens

      ​

## Complexity

... (T-Shirt Sizes S)

**Comment by RobinWitt** [comment]
I think your last task was supposed to be 'Display list of additives'?

Apart from that, it's a really good user story in my opinion.

**Comment by SaschaRadojkovic** [comment]
thank you i have changed this

**Comment by RobinWitt** [comment]
Approved!
