### ISSUE TITLE
Add SearchBar in Additive Component

### ISSUE THREAD

**Issue by SaschaRadojkovic** [SaschaRadojkovic/capstone-project#5]
## Value Proposition

**As a** User
**I want to**have a searchbar
**so that** i can search for additives
​

## Description
![image](https://user-images.githubusercontent.com/16897094/213718680-bcf425f7-2a0b-48f5-87bc-63d4d3a18694.png)
​

## Acceptance Criteria

- [ ] The user can search for additives by name
- [ ] The search results display a list of matching additives in the moment of typing the searchbar
- [ ] if there is no search result the user should see an info "no search results"
- [ ] The user can add additives to their list by clicking the add button beside the searchbar
- [ ] The searchbar component should display only additives in the additive card component
- [ ] The data is not persistant yet     ​

## Tasks

- [ ] import the searchbar component to the additive card component
- [ ] implement it to work only on the additive.json

      ​

## Complexity

... (T-Shirt Sizes XS)

**Comment by ThomasF85** [comment]
Very nice user story!
