### ISSUE TITLE
Persistant Data

### ISSUE THREAD

**Issue by SaschaRadojkovic** [SaschaRadojkovic/capstone-project#7]
## Value Proposition

**As a** User  
**I want** my allergene and additive settings to be saved
**so that** i can see them again after switching between the two categories  
​

## Description

![image](https://user-images.githubusercontent.com/16897094/213760409-2f93218c-bee2-4c6e-9ab4-78af7b715602.png)
​

## Acceptance Criteria

- [ ] The user can switch between the categories without loosing the selected items

      ​

## Tasks

- [ ] Use the local storage for persisting data or create a mongodb atlas database to save the selected items
- [ ] Rewrite the code to make it work
- [ ] for mongodb connection 
  - [ ] create a new cluster on the [mongodb atlas](https://www.mongodb.com/cloud/atlas) 
  - [ ] create two categories `allergens` and `additives`
  - [ ] create `pages/api/ingredients/index.js` and a `pages/api/ingredients/[id].js` 
    - [ ] define a "GET"  and "PUT" method 
  - [ ] create a `db` folder with a `connect.js` and inside the `db` folder create a `models.js`[Example](https://codesandbox.io/s/mongoose-config-mwqfmu)
 
  

      ​

## Complexity

... (T-Shirt Sizes L )

**Comment by AstridOttmann** [comment]
Looks good! 
I would suggest a few changes: 
- in tasks you write 'use localStorage or mongoDB', but afterwards you only mention, how you handle the database - if you have already decided to implement the database here, leave the localStorage out
- 'rewrite the code to make it work' doesn't say anything - leave it out or be more concrete
- complexity is missing (S -M -L ...)
- do you need one or two models? - one for additives and one for allergens - or can both be handled with one model?

**Comment by SaschaRadojkovic** [comment]
Hey , astrid thanks for the review . The complexity is on L  maybe you did not see it . The other ponints i will rewrite

**Comment by SaschaRadojkovic** [comment]
Hey , astrid thanks for the review . The complexity is on L  maybe you did not see it . The other ponints i will rewrite

**Comment by AGeck113** [comment]
Great plan, but i would use a State for now.
