### ISSUE TITLE
Barcode Scanner implementation

### ISSUE THREAD

**Issue by SaschaRadojkovic** [SaschaRadojkovic/capstone-project#9]
## Value Proposition

**As a** User  
**I want to** scan  a product 
**so that** so that i can see the scanned number
​

## Description

![image](https://user-images.githubusercontent.com/16897094/214008550-39d3ef28-f823-4001-a8c7-570f1169deb9.png)
​

## Acceptance Criteria

- [ ] The user should have a barcode scanner that can read and display the scanned number.
- [ ] The user should have navigation to a new page for the barcode scanner and another for settings.
      ​

## Tasks

- [ ] Develop functionality for the barcode scanner.
- [ ] Add a navigation button for activating the scanner in the user interface.
- [ ] Add a navigation button for the settings
- [ ] Create new page for the barcode scanner
- [ ] Create new page for the settings and import the AllergenCard and the AdditiveCard components
- [ ] Integrate the scanner and settings pages into the navigation flow of the app.
      ​

## Complexity

... (T-Shirt Sizes L)

**Comment by AstridOttmann** [comment]
Looks good to me!

Some suggestions to make your Acceptance Criteria more precise: 
- on a second page is a barcode scanner that reads and displays the number of the scanned product
- a navigation is displayed at the bottom of the page
- the navigation has two buttons to navigate between the two sides
- the current page is highlighted

In your Tasks you could use terms as component, folder or file (for the pages),  etc.

**Comment by SaschaRadojkovic** [comment]
thanks for your suggestions :)
